const swaggerAutogen = require('swagger-autogen')()
const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  securityDefinitions: {
    bearerAuth: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      description: "Paste your JWT token here in the format: Bearer <JWT_TOKEN>"
    },
  },
  definitions: {
    Product: {
      $imgurl: "http://images.restapi.co.za/products/product-iphone.png ",
      $name: "iPhone 6s Plus 16Gb",
      $description: "3D Touch. 12MP photos. 4K video.",
      $price: 649,
      $stock_quantity: 2,
      $brandName: "Apple",
      $categoryName: "Phones",
    },
    Admin: {
      $username: "Admin",
      $password: "1234",
    },
    Register: {
      $firstname: "John",
      $lastname: "Doe",
      $username: "User",
      $email: "john@example.com",
      $password: "1234",
      $address: "123 Street, City",
      $phone: "123456789",
    },
    User: {
      $username: "User",
      $password: "1234",
    },
    UserRole: {
      $roleId: 1,
    },
    Search: {
      $name: "iPhone or pho",
      $category: "Phones",
      $brand: "Apple",
    },
    Category: {
      $name: "Phones",
    },
    Brand: {
      $name: "Apple",
    },
    OrderStatus: {
      $newStatus: "Ordered",
    },
    Cart: {
      $productId: 1,
      $quantity: 1
    }
  }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./bin/www')
})